Buliten_Board/Buliten_Board/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include("django.contrib.auth.urls")),
    path('accounts/', include("accounts.urls")),
    path('admin/', admin.site.urls),
    path('', include('board.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Buliten_Board/board/urls.py
from django.urls import path
from .views import (ListingsAll, ListingDetail, CreateListing,
                    EditListing, DeleteListing, AuthorListings, ListingReply, ReplyCreate, AuthorReplies, accept_reply,
                    reject_reply, reply_action, ReplyDetail, cancel_reply)

urlpatterns = [
    path('listings/', ListingsAll.as_view(), name='listings_all'),
    path('listings/<int:pk>', ListingDetail.as_view(), name='listing_detail'),
    path('reply/<int:pk>', ReplyDetail.as_view(), name='reply_detail'),
    path('listings/create/', CreateListing.as_view(), name='listing_create'),
    path('listings/<int:pk>/edit/', EditListing.as_view(), name='listing_edit'),
    path('listings/<int:pk>/delete/', DeleteListing.as_view(), name='listing_delete'),
    path('user/<int:pk>', AuthorListings.as_view(), name='author_list'),
    path('user/<int:pk>/replies', AuthorReplies.as_view(), name='author_replies'),
    path('listings/<int:pk>/replies', ListingReply.as_view(), name='replies'),
    path('listings/<int:pk>/reply_create', ReplyCreate.as_view(), name='reply_create'),
    path('accept_reply/<int:pk>/', accept_reply, name='accept_reply'),
    path('reject_reply/<int:pk>/', reject_reply, name='reject_reply'),
    path('cancel_reply/<int:pk>/', cancel_reply, name='cancel_reply'),
    path('user/<int:pk>/reply_action/', reply_action, name='reply_action'),
]

Buliten_Board/board/models.py
from django.db import models
from django.urls import reverse

from accounts.models import CustomUser as User


class Listing(models.Model):
    """
    Модель объявления.

    Атрибуты:
        author (ForeignKey): Внешний ключ, связывающий объявление с пользователем-автором. При удалении
                             пользователя, связанные с ним объявления также будут удалены.
        dateCreation (DateTimeField): Поле, хранящее дату и время создания объявления. Автоматически
                                     заполняется текущей датой и временем при создании записи.
        category (CharField): Поле с выбором категории объявления из предопределенных вариантов.
        title (CharField): Поле для заголовка объявления (максимальная длина 100 символов).
        text (TextField): Поле для текстового описания объявления.
        image1 (ImageField): Поле для загрузки изображения 1, связанного с объявлением (необязательное поле).
        image2 (ImageField): Поле для загрузки изображения 2, связанного с объявлением (необязательное поле).

    Примечание:
        - Категории объявлений заданы в виде кортежа `CATEGORY_CHOICES`, где первый элемент каждой пары -
          значение для хранения в базе данных, а второй элемент - отображаемое имя категории для пользователей.
        - Для обработки изображений модель использует поля `ImageField` для загрузки и хранения изображений.
    """
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    dateCreation = dateCreation = models.DateTimeField(auto_now_add=True)
    CATEGORY_CHOICES = (
        ('tank', 'Танки'),
        ('healer', 'Хилы'),
        ('dd', 'ДД'),
        ('trader', 'Торговцы'),
        ('guild_master', 'Гилдмастеры'),
        ('quest_giver', 'Квестгиверы'),
        ('blacksmith', 'Кузнецы'),
        ('leatherworker', 'Кожевники'),
        ('alchemist', 'Зельевары'),
        ('spellcaster', 'Мастера заклинаний'),
    )
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)
    title = models.CharField(max_length=100)
    text = models.TextField()
    image1 = models.ImageField(blank=True)
    image2 = models.ImageField(blank=True)

    def get_category_display_ru(self):
        category_choices = dict(self.CATEGORY_CHOICES)
        return category_choices.get(self.category, '')

    def get_absolute_url(self):
        return reverse('listing_detail', args=[str(self.id)])


class Reply(models.Model):
    """
    Модель отклика на объявление.

    Атрибуты:
        listing (ForeignKey): Внешний ключ, связывающий отклик с объявлением. При удалении объявления,
                              связанные с ним отклики также будут удалены.
        author (ForeignKey): Внешний ключ, связывающий отклик с пользователем-автором. При удалении
                             пользователя, связанные с ним отклики также будут удалены.
        text (TextField): Поле для текстового содержания отклика.
        status (BooleanField): Поле, определяющее статус отклика (True - принят, False - не принят).
                              По умолчанию устанавливается в значение False.

    Примечание:
        - Статус отклика определяет, был ли он принят автором объявления или нет.
        - Поля `listing` и `author` связаны с моделями `Listing` и `User` соответственно с помощью
          внешних ключей `ForeignKey`.
    """
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    status = models.BooleanField(default=False)

Buliten_Board/templates/action.html
{% extends 'flatpages/default.html' %}

{% block content %}
   <h1 class="text-center">{{ message }} {{ reply }}</h1>
  <hr>
  <a href="{{ request.META.HTTP_REFERER }}">Вернуться назад</a>
{% endblock content %}

Buliten_Board/templates/author_list.html
{% extends 'flatpages/default.html' %}

{% load tz %}
{% block content %}
   <h1>Мои объявления</h1>
   <h5>{{ time_now|localtime|date:'M d Y' }} {{ time_now|localtime|time:'H:i:s' }}</h5>
   <hr>
   <a href="{% url 'listing_create'%}">Создать объявление</a>
   <hr>
   <a href="{% url 'reply_action' user.id %}">Отклики на мои объявления</a>
   <hr>
   <a href="{% url 'author_replies' user.id %}">Мои отклики</a>
 <hr>
   {% if listings %}
    <style>
        table {
            border-collapse: collapse;
        }

        tr:first-child {
            background-color: green;
        }

        tr:nth-child(even) {
            background-color: white;
        }

        tr:nth-child(odd) {
            background-color: lightblue;
        }

        tr:first-child {
            background-color: green;
        }
    </style>
       <table align="center">
           <tr>
               <td width="15%">Заголовок</td>
               <td width="10%">Категория</td>
               <td width="35%">Текст</td>
               <td colspan="40">Действия</td>
           </tr>
           {% for listing in listings %}
                  <tr>

                      <td>{{ listing.title }}</td>
                      <td>{{ listing.get_category_display_ru }}</td>
                      <td>{{ listing.text }}</td>
                      <td>
                          <a href="{% url 'listing_detail' listing.id %}">Просмотр</a>
                      </td>
                      <td>/<td>
                      <td>
                        <a href="{% url 'listing_edit' listing.id %}">Редактировать</a>
                      </td>
                      <td>/<td>
                      <td>
                        <a href="{% url 'listing_delete' listing.id %}">Удалить</a>
                      </td>
                      <td>/<td>
                      {% if listing.reply_set.all %}
                      <td>
                        <a href="{% url 'replies' listing.id %}">Отклики</a>
                      </td>
                      {% else %}
                      <td>
                        <a>Откликов нет</a>
                      </td>
                      {% endif %}

                  </tr>
           {% endfor %}
       </table>
   {% else %}
       <h2>Объявлений нет!</h2>
   {% endif %}

{% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
{% endblock content %}

Buliten_Board/templates/author_replies.html
{% extends 'flatpages/default.html' %}

{% block content %}
   <h1>Мои отклики</h1>
   <hr>
   <a href="{% url 'author_list' user.id %}">Вернуться к моим объявлениям</a>
 <hr>
   {% if author_replies %}
    <style>
        table {
            border-collapse: collapse;
        }

        tr:first-child {
            background-color: green;
        }

        tr:nth-child(even) {
            background-color: white;
        }

        tr:nth-child(odd) {
            background-color: lightblue;
        }

        tr:first-child {
            background-color: green;
        }
    </style>
       <table align="center">
           <tr>
               <td width="15%">Объявление</td>
               <td width="10%">Категория</td>
               <td width="35%">Текст отклика</td>
               <td colspan="7">Статус</td>
           </tr>
           {% for reply in author_replies %}
                  <tr>
                      <td>{{ reply.listing.title }}</td>
                      <td>{{ reply.listing.get_category_display_ru }}</td>
                      <td>{{ reply.text }}</td>
                      {% if reply.status %}
                        <td>Принят</td>
                      {% else %}
                        <td>Еще не принят</td>
                      {% endif %}
                  </tr>
           {% endfor %}
       </table>
   {% else %}
       <h2>Вы пока не откликнулись ни на одно объявление, либо все ваши отклики отклонены!</h2>
   {% endif %}
{% endblock content %}

Buliten_Board/templates/listing.html
{% extends 'flatpages/default.html' %}

{% block content %}
{% if request.user == listing.author or request.user.is_superuser %}
   <td>
      <a href="{% url 'listing_edit' listing.id %}">Редактировать</a>
   </td>
   <td>/<td>
   <td>
     <a href="{% url 'listing_delete' listing.id %}">Удалить</a>
   </td>
{% endif %}
{% if request.user != listing.author and request.user.is_authenticated %}
    <td>
      {% if has_user_reply or listing.has_user_reply %}
        <p>Отклик отправлен</p>
      {% else %}
        <a href="{% url 'reply_create' listing.id %}">Откликнуться</a>
      {% endif %}
    </td>
{% endif %}
<h1>{{ listing.title }}</h1>
<h1>{{ listing.category }}</h1>
<h1>{{ listing.text }}</h1>
{% if listing.image1 %}
    <img src="{{ listing.image1.url }}" alt="Image 1">
{% endif %}
{% if listing.image2 %}
    <img src="{{ listing.image2.url }}" alt="Image 2">
{% endif %}
<hr>
<a href="/listings/">К объявлениям</a>
{% endblock content %}

Buliten_Board/templates/listing_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Публикация объявления</h1>
<hr>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

Buliten_Board/templates/listing_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление объявления</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}"?</p>
    <input type="submit" value="Удалить!" />
</form>
{% endblock content %}

Buliten_Board/templates/listing_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Внесите правки в объявление</h1>
<hr>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

Buliten_Board/templates/listings_all.html
{% extends 'flatpages/default.html' %}

{% block title %}
Listings
{% endblock title %}
{% load tz %}
{% block content %}
   <h1>Все объявления</h1>
   <h5>{{ time_now|localtime|date:'M d Y' }} {{ time_now|localtime|time:'H:i:s' }}</h5>
   <hr>
   {% if user.is_authenticated %}
   <a href="{% url 'listing_create' %}">Создать объявление</a>
   {% endif %}

   <hr>
   {% if listings %}
    <style>
        table {
            border-collapse: collapse;
        }

        tr:first-child {
            background-color: green;
        }

        tr:nth-child(even) {
            background-color: white;
        }

        tr:nth-child(odd) {
            background-color: lightblue;
        }

        tr:first-child {
            background-color: green;
        }
    </style>
   <table align="center">
       <tr>
           <td width="20%">Автор</td>
           <td width="15%">Заголовок</td>
           <td width="10%">Категория</td>
           <td width="35%">Текст</td>
           <td colspan="3">Действия</td>
       </tr>
       {% for item in has_user_reply %}
           <tr>
               <td>{{ item.listing.author }}</td>
               <td>{{ item.listing.title }}</td>
               <td>{{ item.listing.get_category_display_ru }}</td>
               <td>{{ item.listing.text }}</td>
               <td>
                   <a href="{% url 'listing_detail' item.listing.id %}">Просмотр</a>
               </td>
               {% if request.user == item.listing.author or request.user.is_superuser %}
               <td>/<td>
               <td>
                   <a href="{% url 'listing_edit' item.listing.id %}">Редактировать</a>
               </td>
               <td>/<td>
               <td>
                   <a href="{% url 'listing_delete' item.listing.id %}">Удалить</a>
               </td>
               {% endif %}
               {% if request.user != item.listing.author and request.user.is_authenticated %}
                   <td>/<td>
                   <td>
                       {% if item.has_reply %}
                           <p>Отклик отправлен</p>
                       {% else %}
                           <a href="{% url 'reply_create' item.listing.id %}">Откликнуться</a>
                       {% endif %}
                   </td>
               {% endif %}
           </tr>
       {% endfor %}
   </table>
   {% else %}
       <h2>Объявлений нет!</h2>
   {% endif %}
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
{% endblock content %}

Buliten_Board/templates/reply.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Отклик от {{ reply.author }}</h1>
<h1>на объявление {{ reply.listing.title }}</h1>
<h1>в категории {{ reply.listing.category }}</h1>
<h1>текст отклика: {{ reply.text }}</h1>
<hr>
 <a href="{{ request.META.HTTP_REFERER }}">Вернуться назад</a>
{% endblock content %}

Buliten_Board/templates/reply_action.html
{% extends 'flatpages/default.html' %}

{% block content %}
   <h4>Здесь отклики на все ваши объявления</h4>
<hr>
   <a href="{% url 'author_list' user.id %}">Вернуться к моим объявлениям</a>
{% if replies %}
    <style>
        table {
            border-collapse: collapse;
        }

        tr:first-child {
            background-color: green;
        }

        tr:nth-child(even) {
            background-color: white;
        }

        tr:nth-child(odd) {
            background-color: lightblue;
        }

        tr:first-child {
            background-color: green;
        }
    </style>
   <table align="center">
       <tr>
           <td width="20%">Отклик на объявление</td>
           <td width="20%">Отклик от</td>
           <td width="35%">Текст</td>
           <td colspan="3">Действия</td>
       </tr>
       {% for reply in replies %}
           <tr>
               <td>{{ reply.listing.title }}</td>
               <td>{{ reply.author }}</td>
               <td>{{ reply.text }}</td>
               <td>
                  <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="reply_id" value="{{ reply.id }}">
                    {% if not reply.status %}
                      <button name="action" value="accept">Принять</button>
                      <button name="action" value="reject">Отклонить</button>
                    {% else %}
                      <button disabled>Отклик принят</button>
                      <button name="action" value="cancel">Отмена</button>
                      <button name="action" value="reject">Отклонить</button>
                    {% endif %}
                  </form>
               </td>

           </tr>
       {% endfor %}
   </table>
{% else %}
    <h4>На ваши объявления нет откликов!</h4>
{% endif %}
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
{% endblock content %}

Buliten_Board/templates/reply_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Отклик на объявление</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

Buliten_Board/templates/reply_list.html
{% extends 'flatpages/default.html' %}

{% block content %}
   <h1>Все отклики на объявление "{{listing.title}}"</h1>
<hr>
   <a href="{% url 'author_list' user.id %}">Вернуться к моим объявлениям</a>
   <hr>

    <style>
        table {
            border-collapse: collapse;
        }

        tr:first-child {
            background-color: green;
        }

        tr:nth-child(even) {
            background-color: white;
        }

        tr:nth-child(odd) {
            background-color: lightblue;
        }

        tr:first-child {
            background-color: green;
        }
    </style>
   <table align="center">
       <tr>
           <td width="20%">Отклик от</td>
           <td width="35%">Текст</td>
           <td colspan="40">Действия</td>
       </tr>
       {% for reply in replies %}
           <tr>
               <td>{{ reply.author }}</td>
               <td>{{ reply.text }}</td>
               <td>
                   <a href="{% url 'reply_detail' reply.id %}">Просмотр</a>
               </td>
               {% if not reply.status %}
                <td>/<td>
                <td>
                   <a href="{% url 'accept_reply' reply.id %}">Принять</a>
                </td>
               <td>/<td>
                <td>
                   <a href="{% url 'reject_reply' reply.id %}">Отклонить</a>
                </td>
               {% else %}
               <td>/<td>
                <td>
                   <a> Отклик принят </a>
                </td>
               <td>/<td>
                <td>
                   <a href="{% url 'cancel_reply' reply.id %}">Отмена</a>
                </td>
               <td>/<td>
                <td>
                   <a href="{% url 'reject_reply' reply.id %}">Отклонить</a>
                </td>

               {% endif %}

           </tr>
       {% endfor %}
   </table>
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
{% endblock content %}